name="xe-mbm-beta20.0"
epochs = 200
validate = 1
log = 8
path = "experiments/tieredImageNet/"
num_gpus = 1

[patience]
accuracy-top-1 = 15

[model]
class = "EfficientNetB0"
num_classes = 1010
dropout = 0.2
weights = "IMAGENET1K_V1"

[loss]
class = "CrossEntropyLoss"

[optimizer]
class = "Adam"
lr = 1e-4
weight_decay = 0
amsgrad = true

[lr_scheduler]
class = "CosineAnnealingLR"
T_max = 200
eta_min = 1e-5

[dataloaders.train]
class = "TieredImageNetTrainDataLoader"
path = "datasets/datasets/tieredImageNet/inputs/train"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
batch_size = 64
num_workers = 4

[dataloaders.val]
class = "TieredImageNetValDataLoader"
path = "datasets/datasets/tieredImageNet/inputs/val"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
batch_size = 64
num_workers = 4

[dataloaders.test]
class = "TieredImageNetTestDataLoader"
path = "datasets/datasets/tieredImageNet/inputs/test"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
batch_size = 64
num_workers = 4

[metrics.train.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 1

[metrics.train.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 5

[metrics.val.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 1

[metrics.val.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 5

[metrics.test.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 1

[metrics.test.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/tieredImageNet/encodings/mbm/beta20.0.npy"
top_k = 5
