name="xe-b3p-beta0.3"
epochs = 200
validate = 1
log = 8
path = "experiments/CIFAR100/"
num_gpus = 1

[patience]
accuracy-top-1 = 15

[model]
class = "EfficientNetB0"
num_classes = 100
dropout = 0.2

[loss]
class = "CrossEntropyLoss"

[optimizer]
class = "Adam"
lr = 1e-3
weight_decay = 0
amsgrad = true

[lr_scheduler]
class = "CosineAnnealingLR"
T_max = 200
eta_min = 1e-5

[dataloaders.train]
class = "CIFAR100TrainDataLoader"
path = "datasets/datasets/CIFAR100/inputs"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
batch_size = 64
num_workers = 4

[dataloaders.val]
class = "CIFAR100ValDataLoader"
path = "datasets/datasets/CIFAR100/inputs"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
batch_size = 64
num_workers = 4

[dataloaders.test]
class = "CIFAR100TestDataLoader"
path = "datasets/datasets/CIFAR100/inputs"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
batch_size = 64
num_workers = 4

[metrics.train.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 1

[metrics.train.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 5

[metrics.val.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 1

[metrics.val.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 5

[metrics.test.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 1

[metrics.test.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/CIFAR100/encodings/b3p/beta0.3.npy"
top_k = 5
