name="cd-desc-pca-d500"
epochs = 200
validate = 1
log = 8
path = "experiments/iNaturalist19/"
num_gpus = 1

[patience]
accuracy-top-1 = 15

[model]
class = "EfficientNetB0"
num_classes = 500
dropout = 0.2
weights = "IMAGENET1K_V1"

[loss]
class = "CosineDistanceLoss"

[optimizer]
class = "Adam"
lr = 1e-4
weight_decay = 0
amsgrad = true

[lr_scheduler]
class = "CosineAnnealingLR"
T_max = 200
eta_min = 1e-5

[dataloaders.train]
class = "INaturalist19TrainDataLoader"
path = "datasets/datasets/iNaturalist19/inputs/train"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
batch_size = 64
num_workers = 4

[dataloaders.val]
class = "INaturalist19ValDataLoader"
path = "datasets/datasets/iNaturalist19/inputs/val"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
batch_size = 64
num_workers = 4

[dataloaders.test]
class = "INaturalist19TestDataLoader"
path = "datasets/datasets/iNaturalist19/inputs/test"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
batch_size = 64
num_workers = 4

[metrics.train.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 1

[metrics.train.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 5

[metrics.val.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 1

[metrics.val.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 5

[metrics.test.accuracy-top-1]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 1

[metrics.test.accuracy-top-5]
class = "AlignmentAccuracy"
path_embeddings = "datasets/datasets/iNaturalist19/encodings/desc-pca/ada/austen/d500.npy"
top_k = 5
